app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django.urls import path, re_path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.check, name='home'),

    path('check', views.check, name='demo_check'),

    path('re_fingerprint', views.re_fingerprint, name='document.re_fingerprint'),
    path('re_check', views.re_check, name='document.re_check'),

    path('document', views.document_list, name='document.index'),
    path('document/upload', views.document_upload, name='document.upload'),
    path('document/<uuid:id>', views.document_show, name='document.show'),
    path('document/<uuid:id>/edit', views.document_edit, name='document.edit'),
    path('document/<uuid:id>/delete', views.document_delete, name='document.delete'),
    path('document/<uuid:id>/finish', views.document_finishing, name='document.finish'),
    path('document/<uuid:id>/fingerprint', views.document_fingerprint, name='document.fingerprint'),
    path('document/<uuid:id>/html', views.document_html, name='document.html'),
    path('document/<uuid:id>/pdf', views.document_pdf, name='document.pdf'),
    path('document/<uuid:id>/text', views.document_text, name='document.text'),
    path('document/<uuid:id>/similarity', views.document_similarity, name='document.similarity'),
    path('document/<uuid:id>/check', views.similarity_check, name='document.check'),

    path('dataset', views.dataset_list, name='dataset.index'),
    path('dataset/upload', views.dataset_upload, name='dataset.upload'),
    path('dataset/upload_batch', views.dataset_upload_batch, name='dataset.upload_batch')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("", include("app.urls"))  # add this
]

app/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import resolve_url
import uuid
import mimetypes
import os
from io import StringIO
from pdfminer.high_level import extract_text, extract_text_to_fp
from pdfminer.layout import LAParams
from django.conf import settings
import mammoth

from django.conf import settings

from binfile.winnowing_ngram import winnow as n_winnow
from binfile.winnowing_wordgram import winnow as word_winnow
from binfile.rabin import rabin_word
from binfile.fingerprint import Fingerprint
from django.utils.translation import gettext as _
import json

from django.core.files.base import ContentFile
from django.core.files import File

from django.template.loader import render_to_string

from google.cloud import translate_v2 as translate
from math import *


# Create your models here.

def _get_upload_path(instance, filename):
    ident = uuid.uuid4().hex
    if instance.user:
        path = "document/%s-%s-%s" % (
            ident[:2],
            ident[:8],
            filename
        )
    else:
        path = "unsorted/%s-%s-%s" % (
            ident[:2],
            ident[:8],
            filename
        )

    if not instance.filename:
        instance.filename = filename

    return path


def _similarity_result_path(instance, filename):
    ident = uuid.uuid4().hex
    if instance.content.name:
        instance.content.delete()

    if instance.document:
        path = "similarity/%s%s" % (
            instance.document.filename,
            ".txt"
        )
    else:
        path = "similarity/%s-%s-%s" % (
            ident[:2],
            ident[:8],
            filename
        )

    return path


def _text_path(instance, filename):
    if instance.text.name:
        instance.text.delete()

    path = "text/%s%s" % (
        instance.filename,
        ".txt"
    )

    return path


def _html_path(instance, filename):
    if instance.html.name:
        instance.html.delete()

    path = "html/%s%s" % (
        instance.filename,
        ".html"
    )

    return path


def _fingerprint_path(instance, filename):
    if instance.fingerprint.name:
        instance.fingerprint.delete()

    path = "fingerprint/%s%s" % (
        instance.filename,
        ".fp"
    )

    return path


def _simfmt(point, enable=True):
    if enable:
        # return pow(10, -point) * 100
        return round(point, 3)
    return point


class Document(models.Model):
    class Statuses(models.TextChoices):
        UPLOADED = 'uploaded', _('Uploaded')
        PROCESS = 'process', _('Process')
        FINISHED = 'finished', _('Finished')

    class Meta:
        permissions = (
            ("add_dataset", "can add dataset"),
            ("change_dataset", "can change dataset"),
            ("delete_dataset", "can delete dataset"),
            ("view_dataset", "can view dataset"),
        )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    filename = models.CharField(max_length=128, db_index=True, blank=True)
    original_filename = models.CharField(max_length=128, blank=True)
    metadata = models.TextField(blank=True, null=True)
    lang = models.CharField(max_length=50, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=191, null=True, blank=True)
    author = models.CharField(max_length=191, null=True, blank=True)
    content = models.FileField(upload_to=_get_upload_path, max_length=191, unique=True, db_index=True)
    text = models.FileField(upload_to=_text_path, max_length=191)
    html = models.FileField(upload_to=_html_path, max_length=191)
    keyword = models.CharField(max_length=191, null=True, blank=True)
    size_bytes = models.IntegerField(default=0, db_index=True)
    fingerprint = models.FileField(upload_to=_fingerprint_path, max_length=191)
    is_dataset = models.BooleanField(default=False)
    similarities = models.ManyToManyField('self', through='Similarity', symmetrical=False, related_name='similar_to')
    status = models.CharField(max_length=10, choices=Statuses.choices, default=Statuses.UPLOADED)
    created = models.DateTimeField(auto_now_add=True, editable=False, help_text="DB Insertion Time")
    modified = models.DateTimeField(auto_now=True, editable=False, help_text="DB Modification Time")

    def __str__(self):
        return "{}".format(self.content.name)

    def add_similarity(self, dataset, cosine=0.0, jaccard=0.0, dice=0.0, manhattan=0.0, minkowski=0.0, mahalanobis=0.0, euclidean=0.0, weighted=0.0):
        similarity, created = Similarity.objects.update_or_create(
            document=self,
            dataset=dataset,
        )

        similarity.cosine = cosine
        similarity.jaccard = jaccard
        similarity.dice = dice
        similarity.manhattan = manhattan
        similarity.minkowski = minkowski
        similarity.mahalanobis = mahalanobis
        similarity.euclidean = euclidean
        similarity.weighted = weighted
        similarity.save()

        return similarity

    def remove_similarity(self, dataset):
        Similarity.objects.filter(
            document=self,
            dataset=dataset).delete()
        return

    def get_datasets(self):
        return self.similarities.filter(
            to_datasets__document=self)

    def get_similarity(self, as_table=False):
        sort = ['-dice', '-jaccard', '-cosine', 'euclidean', 'weighted', 'minkowski', 'manhattan']
        # sort = ['-euclidean', '-weighted', '-manhattan']
        similarity = Similarity.objects.filter(document=self).order_by(*sort)[:10]
        result = []
        if as_table:
            res = list(similarity)
            # jsoning = []
            for item in res:
                # jsoning.append(item.serialize())
                result.append(item)

            # pa = os.path.join(settings.MEDIA_ROOT, 'export', self.id.hex+'.json')
            # with open(pa, mode='w+') as fa:
            #     aa = json.dumps(jsoning)
            #     fa.write(aa)


            result = render_to_string('document/includes/similarity-table.html', {'data': result})
        else:
            result = similarity
            result.label = [a[:15] for a in similarity.values_list('dataset__original_filename', flat=True)]
            result.cosine = list(similarity.values_list('cosine', flat=True))
            result.dice = list(similarity.values_list('dice', flat=True))
            result.jaccard = list(similarity.values_list('jaccard', flat=True))
            
            result.minkowski = [_simfmt(a) for a in similarity.values_list('minkowski', flat=True)]
            result.manhattan = [_simfmt(a) for a in similarity.values_list('manhattan', flat=True)]
            result.euclidean = [_simfmt(a) for a in similarity.values_list('euclidean', flat=True)]
            result.weighted = [_simfmt(a) for a in similarity.values_list('weighted', flat=True)]
            result.mahalanobis = [_simfmt(a, False) for a in similarity.values_list('mahalanobis', flat=True)]

        return result

    def get_compared_to(self):
        return self.similar_to.filter(
            form_documents__dataset=self)

    def save(self, *args, **kwargs):
        if self.content.name:
            self.size_bytes = self.content.size
            self.filename, _ = os.path.splitext(os.path.basename(self.content.path))

        super(Document, self).save(*args, **kwargs)

    def delete(self, using=None, keep_parents=False):
        if self.fingerprint.name != '' and self.fingerprint.storage.exists(self.fingerprint.name):
            self.fingerprint.delete()
        if self.html.name != '' and self.html.storage.exists(self.html.name):
            self.html.delete()
        if self.text.name != '' and self.text.storage.exists(self.text.name):
            self.text.delete()
        try:
            if self.content.name != '' and self.content.storage.exists(self.content.name):
                self.content.delete()
        except PermissionError:
            print("permission error : ", self.content.path)

        super().delete()

    def extract_content(self):
        self.status = Document.Statuses.PROCESS

        text = StringIO()
        html = StringIO()

        _, ext = os.path.splitext(self.content.path)
        with self.content as file:
            if ext == ".pdf":
                laparams = LAParams(line_margin=0.1)
                setattr(laparams, 'all_texts', True)
                extract_text_to_fp(self.content, text, laparams=laparams)
                extract_text_to_fp(self.content, html, laparams=laparams, output_type='html', codec=None, scale=1.9, rotation=0, layoutmode='normal')
            elif ext in [".docx", ".doc"]:
                result = mammoth.convert_to_html(file)
                html.write(result.value)
                result = mammoth.extract_raw_text(file)
                text.write(result.value)

        with ContentFile(content=text.getvalue().encode("utf-8")) as file:
            self.text.save(name='any', content=file)

        with ContentFile(content=html.getvalue().encode("utf-8")) as file:
            self.html.save(name='any', content=file)

        return "{}".format(self.text.name)

    def translate(self):
        if settings.TRANSLATION_ENABLED:
            text = self.get_text()
            if text is None:
                return

            # os.environ['GRPC_DNS_RESOLVER'] = 'native'
            translate_client = translate.Client()

            try:
                result = translate_client.translate(text, target_language="id")
                self.lang = result['detectedSourceLanguage']
                with ContentFile(content=result['translatedText'].encode("utf-8")) as file:
                    self.text.save(name='any', content=File(file))
                return True
            except:

app/templates/includes/footer.html
<footer class="c-footer">
    <div>
        <a href="#">Penelitian Evaluasi Algoritma Rabin Karp</a>
    </div>
    <div class="ml-auto">&copy;<a href="#">F. TEKNIK UNMUH PONOROGO</a></div>
</footer>
 

app/templates/includes/navigation.html
      <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
            <button class="c-header-toggler c-class-toggler d-lg-none mr-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show"><span class="c-header-toggler-icon"></span></button><a class="c-header-brand d-sm-none" href="#"><img class="c-header-brand" src="/static/assets/brand/coreui-base.svg" width="97" height="46" alt="CoreUI Logo"></a>
            <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true"><span class="c-header-toggler-icon"></span></button>
{#            <ul class="c-header-nav d-md-down-none">#}
{#              <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Dashboard</a></li>#}
{#              <!-- <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Users</a></li> -->#}
{#              <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Settings</a></li>#}
{#            </ul>#}
            <ul class="c-header-nav ml-auto mr-4">
              <!-- <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                  </svg></a></li>
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-list-rich"></use>
                  </svg></a></li>
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                  </svg></a></li> -->
              <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                  <div class="c-avatar"><img class="c-avatar-img" src="/static/assets/img/avatars/6.jpg" alt="user@email.com"></div>
                </a>
                <div class="dropdown-menu dropdown-menu-right pt-0">
{#                  <div class="dropdown-header bg-light py-2"><strong>Account</strong></div><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>#}
{#                    </svg> Updates<span class="badge badge-info ml-auto">42</span></a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>#}
{#                    </svg> Messages<span class="badge badge-success ml-auto">42</span></a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>#}
{#                    </svg> Tasks<span class="badge badge-danger ml-auto">42</span></a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-comment-square"></use>#}
{#                    </svg> Comments<span class="badge badge-warning ml-auto">42</span></a>#}
{#                  <div class="dropdown-header bg-light py-2"><strong>Settings</strong></div><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>#}
{#                    </svg> Profile</a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>#}
{#                    </svg> Settings</a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-credit-card"></use>#}
{#                    </svg> Payments<span class="badge badge-secondary ml-auto">42</span></a><a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-file"></use>#}
{#                    </svg> Projects<span class="badge badge-primary ml-auto">42</span></a>#}
{#                  <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                    <svg class="c-icon mr-2">#}
{#                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>#}
{#                    </svg> Lock Account#}
{#                    </a>#}
                    <a class="dropdown-item" href={% url 'logout' %} >
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                    </svg> Logout</a>
                </div>
              </li>
            </ul>
            <div class="c-subheader px-3">
              <!-- Breadcrumb-->
              <ol class="breadcrumb border-0 m-0">
                <li class="breadcrumb-item">Home</li>
                <li class="breadcrumb-item"><a href="#">Admin</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
                <!-- Breadcrumb Menu-->
              </ol>
            </div>
          </header>
    

app/templates/includes/scripts.html
    <!-- CoreUI and necessary plugins-->
    <script src="/static/assets/vendors/pace-progress/js/pace.min.js"></script>
    <script src="/static/assets/vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>

app/templates/includes/sidebar.html
    <div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
            <div class="c-sidebar-brand"><img class="c-sidebar-brand-full" src="/static/assets/brand/coreui-base-white.svg" width="118" height="46" alt="CoreUI Logo"><img class="c-sidebar-brand-minimized" src="/static/assets/brand/coreui-signet-white.svg" width="118" height="46" alt="CoreUI Logo"></div>
            <ul class="c-sidebar-nav">
              <!-- <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="/">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>
                  </svg> Dashboard<span class="badge badge-info">NEW</span>
                </a>
              </li> -->
              <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{% url 'demo_check' %}">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>
                  </svg> Check How it works <span class="badge badge-info">DEMO</span>
                </a>
              </li>
            {% if perms.app.view_document %}
              <li class="c-sidebar-nav-title">Documents</li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-file"></use>
                  </svg> My Documents
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'document.index' %}"><span class="c-sidebar-nav-icon"></span> All</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'document.upload' %}"><span class="c-sidebar-nav-icon"></span> Upload</a></li>
                </ul>
              </li>
            {% endif %}

            {% if perms.app.view_dataset %}
              <li class="c-sidebar-nav-title">System</li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-folder"></use>
                  </svg> Dataset
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'dataset.index' %}"><span class="c-sidebar-nav-icon"></span> All</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'dataset.upload' %}"><span class="c-sidebar-nav-icon"></span> Upload</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{% url 'dataset.upload_batch' %}"><span class="c-sidebar-nav-icon"></span> Upload Batch</a></li>
                </ul>
              </li>
            {% endif %}

              <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href={% url 'logout' %} >
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg> Logout
                </a>
              </li>

              <!-- <li class="c-sidebar-nav-divider"></li>
              <li class="c-sidebar-nav-title">Extras</li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-star"></use>
                  </svg> Pages
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href={% url 'register' %} target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                      </svg> Register
                    </a>
                  </li>
                  <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="/error-404.html" target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                      </svg> Error 404
                    </a>
                  </li>
                  <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="/error-500.html" target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                      </svg> Error 500
                    </a>
                  </li>
                </ul>
              </li>
              <li class="c-sidebar-nav-item mt-auto">
                <a class="c-sidebar-nav-link c-sidebar-nav-link-success" 
                  href="https://appseed.us/admin-dashboards/django-dashboard-coreui">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-cloud-download"></use>
                  </svg> Product Info
                </a>
              </li> -->
            </ul>
      <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
    </div>
      