app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django.urls import path, re_path
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.check, name='home'),

    path('check', views.check, name='demo_check'),

    path('re_fingerprint', views.re_fingerprint, name='document.re_fingerprint'),
    path('re_check', views.re_check, name='document.re_check'),

    path('document', views.document_list, name='document.index'),
    path('document/upload', views.document_upload, name='document.upload'),
    path('document/<uuid:id>', views.document_show, name='document.show'),
    path('document/<uuid:id>/edit', views.document_edit, name='document.edit'),
    path('document/<uuid:id>/delete', views.document_delete, name='document.delete'),
    path('document/<uuid:id>/finish', views.document_finishing, name='document.finish'),
    path('document/<uuid:id>/fingerprint', views.document_fingerprint, name='document.fingerprint'),
    path('document/<uuid:id>/html', views.document_html, name='document.html'),
    path('document/<uuid:id>/pdf', views.document_pdf, name='document.pdf'),
    path('document/<uuid:id>/text', views.document_text, name='document.text'),
    path('document/<uuid:id>/similarity', views.document_similarity, name='document.similarity'),
    path('document/<uuid:id>/check', views.similarity_check, name='document.check'),

    path('dataset', views.dataset_list, name='dataset.index'),
    path('dataset/upload', views.dataset_upload, name='dataset.upload'),
    path('dataset/upload_batch', views.dataset_upload_batch, name='dataset.upload_batch')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("", include("app.urls"))  # add this
]

app/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2020 - Winnowing Similarity Measurement
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from app.models import Document


class InputForm(forms.Form):
    origin = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder" : "Text Asli",
                "class" : "form-control",
            }
        )
    )
    referer = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder" : "Text Pembanding",
                "class" : "form-control",
            }
        )
    )

    gram_option = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class" : "form-control",
            }
        ), 
        choices=[(b, b) for b in range(1, 16)]
        )
    
    winnow_option = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class" : "form-control",
            }
        ), 
        choices=[(1, 'wordgram')]
        )

    plag_option = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class" : "form-control",
            }
        ), 
        choices=[(1, 'Winnowing'), (2, 'Rabin-Karp')]
        )
    debug = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class" : "form-control",
            }
        ), 
        choices=[(0, 'Off'), (1, 'On')]
        )


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        widgets = {
            'title': forms.TextInput(
                attrs={
                    "placeholder": "Judul Dokumen",
                    "class": "form-control",
                }
            ),
            'author': forms.TextInput(
                attrs={
                    "placeholder": "Pengarang",
                    "class": "form-control",
                }
            ),
            'content': forms.FileInput(
                attrs={
                    "placeholder": "File",
                    "class": "custom-file-input",
                    "accept": ".doc,.docx,.pdf"
                }
            ),
            'keyword': forms.TextInput(
                attrs={
                    "placeholder": "Keyword",
                    "class": "form-control",
                }
            ),
            'lang': forms.TextInput(
                attrs={
                    "placeholder": "Language",
                    "class": "form-control",
                }
            ),
        }
        fields = ['title', 'author', 'content', 'keyword', 'lang']

app/templates/check.html
{% extends "layouts/base-site.html" %}

{% block title %} Check How it Work {% endblock %}

{% block content %}

<div class="container-fluid">
  <div class="fade-in">
    <div class="card">
      <div class="card-body">
        <form action="{% url 'demo_check' %}" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-6">
              {{ form.origin }}
            </div>
            <div class="col-sm-12 col-md-12 col-lg-6">
              {{ form.referer }}
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-sm-12  col-lg-3">
              <label for="id_gram_option">Grams :</label>
              {{ form.gram_option }}
            </div>
            <div class="col-sm-12 col-lg-3">
              <label for="id_winnow_option">Mode :</label>
              {{ form.winnow_option }}
            </div>
            <div class="col-sm-12 col-lg-3">
              <label for="id_winnow_option">Fingerprinting Options :</label>
              {{ form.plag_option }}
            </div>
            <div class="col-sm-12 col-lg-3">
              <label for="id_debug">Debug :</label>
              {{ form.debug }}
            </div>
            <br>

          </div>
          <div class="row" style="margin-top: 15px;">
            <div class="col-sm-12">
              <button type="submit" class="btn btn-primary float-right">Check</button>
            </div>
          </div>
        </form>
      </div>
    </div>

    {% if data %}
    {% if form.debug.value == '1' %}
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <h4>Origin (first 10)</h4>
            <h5>Sanitize</h5>
            <p>
              {% if form.winnow_option.value == '1' %}
              {% for s in data.origin.steps.sanitize %}
              {{ s|add:" " }}
              {% endfor %}
              {% else %}
              {{ data.origin.steps.sanitize }}
              {% endif %}
              ...
            </p>
          </div>
          <div class="col-6">
            <h4>Referer (first 10)</h4>
            <h5>Sanitize</h5>
            <p>
              {% if form.winnow_option.value == '1' %}
              {% for s in data.referer.steps.sanitize %}
              {{ s|add:" " }}
              {% endfor %}
              {% else %}
              {{ data.referer.steps.sanitize }}
              {% endif %}
              ...
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-6">

            <h5>Grams</h5>
            <p>
              {% if form.winnow_option.value == '1' %}
              {% for s in data.origin.steps.gram %}
              [
              {% for si in s %}
              {{ si|add:" " }}
              {% endfor %}
              ]
              {% endfor %}
              {% else %}
              {% for s in data.origin.steps.gram %}
              {{ s|add:" " }}
              {% endfor %}
              {% endif %}
              ...
            </p>
          </div>
          <div class="col-6">


            <h5>Grams</h5>
            <p>
              {% if form.winnow_option.value == '1' %}
              {% for s in data.referer.steps.gram %}
              [
              {% for si in s %}
              {{ si|add:" " }}
              {% endfor %}
              ]
              {% endfor %}
              {% else %}
              {% for s in data.referer.steps.gram %}
              {{ s|add:" " }}
              {% endfor %}
              {% endif %}
              ...
            </p>
          </div>
        </div>
        <div class="row">

          <div class="col-6">
            <h5>Hashes</h5>
            <p>
              {% for s in data.origin.steps.hashes %}
              {{ s.1 }}
              {% endfor %}
              ...
            </p>
          </div>
          <div class="col-6">


            <h5>Hashes</h5>
            <p>
              {% for s in data.referer.steps.hashes %}
              {{ s.1 }}
              {% endfor %}
              ...
            </p>
          </div>
        </div>
        <div class="row">


          <div class="col-6">
            <h5>Windows</h5>
            <p>
              {% for s in data.origin.steps.windows %}
              {
              {% for si in s %}
              {{ si.1 }}
              {% endfor %}
              }
              {% endfor %}
              ...
            </p>
          </div>
          <div class="col-6">

            <h5>Windows</h5>
            <p>
              {% for s in data.referer.steps.windows %}
              {
              {% for si in s %}
              {{ si.1 }}
              {% endfor %}
              }
              {% endfor %}
              ...
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-6">

            <h5>Fingerprint</h5>
            <div class="scroll">
              {% for s in data.origin.data %}
              {{ s }}
              {% endfor %}
            </div>
          </div>
          <div class="col-6">
            <h5>Fingerprint</h5>
            <div class="scroll">
              {% for s in data.referer.data %}
              {{ s }}
              {% endfor %}
            </div>
          </div>



        </div>
      </div>
    </div>
    {% endif %}
    <div class="card">
      <div class="card-body">
        <div class="row">
          {% for index,da in data.kmp.items %}

          <div class="col-6">
            <h4>KMP</h4>
            <h5>String {{ index }}</h5>
            <div class="scroll">
              {{ da|safe }}


            </div>
          </div>
          {% endfor %}

        </div>
        <div class="row">
          <div class="col">
            <h4>Measurement Result</h4>
          </div>
        </div>
        {% for i,d in data.measures.items %}
        <div class="row my-1">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <strong>{{ i }} </strong>
          </div>
          <div class="col-lg-9 col-md-6 col-sm-6">
            <div class="clearfix">
              <div class="float-left"><strong>{{d}}%</strong></div>
              <!-- <div class="float-right"><small class="text-muted">Jun 11, 2015 - Jul 10, 2015</small></div> -->
            </div>
            <div class="progress progress-xs">
              <div class="progress-bar bg-success" role="progressbar" style="width: {{d}}%" aria-valuenow="{{d}}"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
</div>

{% endblock content %}

{% block javascripts %}

<script src="/static/assets/vendors/@coreui/coreui-chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="/static/assets/js/main.js"></script>

{% endblock javascripts %}

app/templates/dataset_list.html
{% extends "layouts/base-site.html" %}

{% block title %} Dataset List {% endblock %} 

{% block content %}

    <div class="container-fluid">
      <div class="fade-in">
        <div class="card">
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Filename</th>
                  <th>Title</th>
                  <th>Created At</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for doc in documents  %}
                <tr>
                  <td>{{ doc.id }}</td>
                  <td>{{ doc.filename }}</td>
                  <td>{{ doc.title }}</td>
                  <td>{{ doc.created }}</td>
                  <td>{{ doc.status }}</td>
                  <td>{{ doc.get_actions | safe }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

{% block javascripts %}

<script src="/static/assets/vendors/@coreui/coreui-chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="/static/assets/js/main.js"></script>

{% endblock javascripts %}

app/templates/document_list.html
{% extends "layouts/base-site.html" %}

{% block title %} Document List {% endblock %} 

{% block content %}

    <div class="container-fluid">
      <div class="fade-in">
        <div class="card">
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Filename</th>
                  <th>Title</th>
                  <th>Fingerprint</th>
                  <th>Created At</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for doc in documents  %}
                <tr>
                  <td>{{ doc.id }}</td>
                  <td>{{ doc.filename }}</td>
                  <td>{{ doc.title }}</td>
                  <td>{{ doc.fingerprint }}</td>
                  <td>{{ doc.created }}</td>
                  <td>{{ doc.status }}</td>
                  <td>{{ doc.get_actions | safe }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

{% block javascripts %}

<script src="/static/assets/vendors/@coreui/coreui-chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="/static/assets/js/main.js"></script>

{% endblock javascripts %}

app/templates/upload_document.html
{% extends "layouts/base-site.html" %}

{% block title %} Dashboard {% endblock %} 

{% block content %}

    <div class="container-fluid">
      <div class="fade-in">
        <div class="card">
          <div class="card-body">
            <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-6">
                    {{ form.title.label_tag }}
                    {{ form.title }}
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6">
                    {{ form.author.label_tag }}
                    {{ form.author }}
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6">
                    {{ form.content.label_tag }}
                    {{ form.content }}
                </div>
              </div>
              <div class="row mt-2">
                <div class="col-sm-12 col-lg-3 mt-4">
                  <button type="submit" class="btn btn-primary float-right">Upload</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

{% block javascripts %}

<script src="/static/assets/vendors/@coreui/coreui-chartjs/js/coreui-chartjs.bundle.js"></script>
<script src="/static/assets/js/main.js"></script>

{% endblock javascripts %}